### ISSUE TITLE
Help with the implementation

### ISSUE THREAD

**Issue by EstebanC02** [heart/CarBode-Barcode-Scanner-For-SwiftUI#1]
Hello, thank you very much for the library, the truth is I'm starting with iOS development and do not understand many things...

I'm testing your library to integrate it into my project, but I get an error because can't find the CarBode reference.

![Screen Shot 2019-11-04 at 11 36 26 AM](https://user-images.githubusercontent.com/11792308/68139409-18078000-fef8-11e9-99e6-f21595c2214c.png)

![Screen Shot 2019-11-04 at 11 36 42 AM](https://user-images.githubusercontent.com/11792308/68139450-22c21500-fef8-11e9-8725-9265eab7a410.png)

I already integrated CarBode via SPM

![Screen Shot 2019-11-04 at 11 40 14 AM](https://user-images.githubusercontent.com/11792308/68139434-1f2e8e00-fef8-11e9-92c6-ebf10e33a935.png)

I hope you can help me! Thanks

**Comment by heart** [comment]
Hello @EstebanC02,

Thank you for report this issue
and sorry for my mistake I forget to set struct and initialize method to public

please try to update the package again

<img width="656" alt="Screen Shot 2562-11-05 at 11 43 54" src="https://user-images.githubusercontent.com/167836/68179322-fecb0600-ffc1-11e9-9ce8-868522f93ed1.png">
