### ISSUE TITLE
convert to class?

### ISSUE THREAD

**Issue by AMBIENTE1** [heart/CarBode-Barcode-Scanner-For-SwiftUI#10]
Hello, thank you very much, nice work!
It is possible convert ModalScannerView (struct) to class with UIView?

**Comment by heart** [comment]
Thank you @AMBIENTE1 

Are you using SwiftUI?

**Comment by AMBIENTE1** [comment]
uff, thx for kick! I made it over:

import UIKit
import SwiftUI

class ViewController: UIViewController {

    @IBOutlet var scannerbar: UIView!
      
    override func viewDidLoad() {
            super.viewDidLoad()
           let controller = UIHostingController(rootView: ModalScannerView())
          
           addChild(controller)
           controller.view.frame = scannerbar.bounds
           scannerbar.addSubview(controller.view)
           controller.didMove(toParent: self)
           
        }
       
    
    
 struct ModalScannerView: View {....

**Comment by heart** [comment]
Hi @AMBIENTE1 
Nobody wants to kick you I just confusing and I don't understand the question enough.

You don't need to convert it to a class
you can put it on a normal view

```Swift
import UIKit
import SwiftUI
import CarBode

class ViewController: UIViewController {

    override func viewDidLoad() {
        super.viewDidLoad()
        
        let controller = UIHostingController(rootView: ScannerView() )
        view.addSubview(controller.view)
    }
    
}

struct ScannerView: View {
    
    @State var barcodeValue = ""
    @State var torceIsOn = false
    
    var body: some View {
        CBScanner(supportBarcode: [.qr, .code128])
            .interval(delay: 1.0)
            .found{
                self.barcodeValue = $0
            }
            .simulator(mockBarCode: "MOCK BARCODE DATA 1234567890")
            .torchLight(isOn: self.torceIsOn)
            .frame(minWidth: 0, maxWidth: .infinity, minHeight: 400, maxHeight: 400, alignment: .topLeading)
    }
    
}
```

**Comment by AMBIENTE1** [comment]
OK, and how can delegate variable scannerbar to textLabel.text in class or into another func in class?? I'm Sorry, but I never used struct... :(

**Comment by heart** [comment]
Actually I think if you just only want to put a barcode scanner to view
but don't want to take any features and benefits from SwiftUI

You don't need to use SwiftUI inside the normal ViewController it's will make your project more complicated.

You can follow this tutorial trust me it's very easier
https://www.hackingwithswift.com/example-code/media/how-to-scan-a-barcode

Because of this component design for pure SwiftUI

**Comment by AMBIENTE1** [comment]
Yes, you're right. This solution is better for me.
Thank you very much for your support!

Carlos

**Comment by heart** [comment]
You're welcome pal
