### ISSUE TITLE
not Trigger 

### ISSUE THREAD

**Issue by lutzmuschischutz** [heart/CarBode-Barcode-Scanner-For-SwiftUI#11]
CBScanner.....
.interval(delay: 2.5)...

not Triggering anymore if App sceneDidBecomeActive. what can i do without reloading Page?

**Comment by heart** [comment]
Hi @lutzmuschischutz can you show me the code 
I just want to run it to find the problem

**Comment by lutzmuschischutz** [comment]
`CBScanner(supportBarcode: [.qr, .code128]) //Set type of barcode you want to scan
                    .torchLight(isOn: self.torceIsOn) // Turn torch light on/off
                    .interval(delay: 2.5) //Event will trigger every 5 seconds
                       .found{
                        
                        print($0)
                        
                      }`

**Comment by lutzmuschischutz** [comment]
its happen if the device gets an notification or you swipe the notif.center down.

`CBScanner(supportBarcode: [.qr, .code128])
                .torchLight(isOn: self.torceIsOn)
                .interval(delay: 2.5)
                   .found{
                    
                    self.turnLight()
                    
                    print($0)
                    
                  }`

**Comment by heart** [comment]
Hello @lutzmuschischutz  
good news 
I just fixed this issue
please update `Carbode` to version `1.4.1`
