### ISSUE TITLE
forgot to init?

### ISSUE THREAD

**Issue by L1cardo** [heart/CarBode-Barcode-Scanner-For-SwiftUI#15]
keep getting this
![image](https://user-images.githubusercontent.com/33802186/81841119-86e72500-957c-11ea-9a70-7b611cd47955.png)

**Comment by heart** [comment]
Hello @L1cardo
Thank you and sorry for my mistake 
It's fixed in v.1.4.3

**Comment by nylonW** [comment]
I have the same issue for CBScanner in 2.0.0
```typealias OnFound = (BarcodeData)->Void``` 
has to be public

**Comment by heart** [comment]
Hi @nylonW 
Sorry for my mistake I just fixed it in v.2.0.1
