### ISSUE TITLE
box around found codes?

### ISSUE THREAD

**Issue by VoordeMensen** [heart/CarBode-Barcode-Scanner-For-SwiftUI#17]
Thanks for creating this, it really helps me out!! 

One question, how difficult would it be to draw a rectangle around found codes? Using transformedMetadataObject on the previewLayer like explained here https://www.appcoda.com/barcode-reader-swift/ ?

Thanks!

**Comment by heart** [comment]
Hello @VoordeMensen,
Thank you for a suggestion of the new interesting feature 
I will try to do it

**Comment by heart** [comment]
Hi @VoordeMensen 
I have a good news. I just released the new version 2.1.0 that you can draw a box around the barcode.
