### ISSUE TITLE
Support switching to front camera? 

### ISSUE THREAD

**Issue by nicelion** [heart/CarBode-Barcode-Scanner-For-SwiftUI#18]
I think it would be awesome to have built in ability for the user to switch which camera to use for scanning.

**Comment by heart** [comment]
Thank you @nicelion
I will do it this week end

**Comment by VoordeMensen** [comment]
+1

**Comment by heart** [comment]
V.2.0.0 you can switch front and back camera
But this version I has changed many things  please look at readme
