### ISSUE TITLE
iOS 14 beta

### ISSUE THREAD

**Issue by beboprich** [heart/CarBode-Barcode-Scanner-For-SwiftUI#19]
I've tried my app on iOS 14 beta and is working in a strange way.

If I open the View that contains Carbode it takes a photo immediately, is not waiting to recognize de barcode.

I think that you should probably know.

**Comment by heart** [comment]
Thank you @beboprich I never try iOS 14 before but i will test it

**Comment by vdkdamian** [comment]
Any news about this topic?

**Comment by heart** [comment]
Hi @novemTeam  and @beboprich 
Sorry for bugs
I just release version 1.5.0 that fixed this issue
