### ISSUE TITLE
AVMetadataMachineReadableCodeObject has no member corners

### ISSUE THREAD

**Issue by seanlu99** [heart/CarBode-Barcode-Scanner-For-SwiftUI#30]
![Screen Shot 2020-10-13 at 4 55 35 PM](https://user-images.githubusercontent.com/12735282/95915639-6f9fa400-0d75-11eb-806c-8c979da5d0eb.png)
Getting this error when I updated to v2.1.0. Error is not present on v2.0.1.
I'm running Xcode 12.0.1.

**Comment by heart** [comment]
Thankyou @seanlu99 for report the issue

 This error only happen in Simulator I will fix it.

**Comment by heart** [comment]
@seanlu99 I fixed it in v.2.1.1
