### ISSUE TITLE
mockBarCode does not work

### ISSUE THREAD

**Issue by seanlu99** [heart/CarBode-Barcode-Scanner-For-SwiftUI#31]
![Screen Shot 2020-10-13 at 5 07 34 PM](https://user-images.githubusercontent.com/12735282/95916414-98746900-0d76-11eb-95ed-3ffb954855b6.png)
This is a screenshot of my output when I click on the `CBScanner` in simulator. It always prints "Mock Value" instead of the `BarcodeData` object I pass in. I'm using v2.0.1 and Xcode 12.0.1 with iPhone 11 iOS 14.0 simulator

**Comment by heart** [comment]
fixed in 2.1.1

```Swift
    CBScanner(
        supportBarcode: .constant([.qr, .code128]), //Set type of barcode you want to scan
        scanInterval: .constant(5.0), //Event will trigger every 5 seconds
        mockBarCode: .constant(BarcodeData(value:"Mocking data", type: .qr))
    ){
        //When you click the button on screen mock data will appear here
        print("BarCodeType =",$0.type.rawValue, "Value =",$0.value)
    }
```
