### ISSUE TITLE
Export Generated Barcode to Printer or Camera Roll

### ISSUE THREAD

**Issue by zfisher323** [heart/CarBode-Barcode-Scanner-For-SwiftUI#33]
Hi! Love the code... quick question. I would really like to be able to export the generated barcode to a printer or camera roll...

Is that something you could add? I was hoping I could just use something like the following extension:
extension UIImage {
    convenience init(view: CBBarcodeView) {
        UIGraphicsBeginImageContext(view.frame.size)
        view.layer.render(in:UIGraphicsGetCurrentContext()!)
        let image = UIGraphicsGetImageFromCurrentImageContext()
        UIGraphicsEndImageContext()
        self.init(cgImage: image!.cgImage!)
    }
}

And then turn CBBarcodeView into an image that I could export, but CBBarcodeView doesn't have a size or layer for the UIGraphiucsBeginImageContext call...

Thoughts? Thanks again! Zack

**Comment by heart** [comment]
Hello @zfisher323  

Please update to version 2.2.0
Then do like this

```Swift
@State var barcodeImage: UIImage?
...
....
...
CBBarcodeView(data: $dataString,
                barcodeType: $barcodeType,
                orientation: $rotate)
                 { image in
                    self.barcodeImage = image  // You can access the barcode image here.
                 }
                .frame(minWidth: 0, maxWidth: .infinity, minHeight: 400, maxHeight: 400, alignment: .topLeading)
```

**Comment by zfisher323** [comment]
Brilliant! Thanks so much!!!!

**Comment by zfisher323** [comment]
Hello @heart Hmm, I'm trying now to create a button that will save that image to my photo library, but it doesn't seem to work:

Button(action: { UIImageWriteToSavedPhotosAlbum(self.barcodeImage!, nil, nil, nil) } and that prompts the alert asking if I have permission to save the file, but then nothing actually appears in my photo album... should I be accessing the image in a different way? I even tried adding the UIImageWriteToSavedPhotosAlbum inside the QR generator itself (which would probably  try to save an image each time I changed the text) but even that wouldn't add the image to the photos library... Thoughts?
