### ISSUE TITLE
Exporting Barcode Image

### ISSUE THREAD

**Issue by zfisher323** [heart/CarBode-Barcode-Scanner-For-SwiftUI#35]
Hello! Thanks so much for adding code in 2.2 to access the image file... however, I can't seem to actually get it to save to the camera roll... I'm trying with a very basic Button(action: { UIImageWriteToSavedPhotosAlbum(self.barcodeImage!, nil, nil, nil) } and it asks for camera access and completes the action, but nothing actually shows up in the camera roll... Can I not access the image this way? I'm sorry for my confusion, I'm relatively new to swift and can't figure out how to access the QR code to export it out of the app (which I'm assuming is something you want it to be able to do!) Thanks, Zack

**Comment by zfisher323** [comment]
Hi! Just following up on these potential feature... happy to donate a little to the cause if you can get this working!

**Comment by heart** [comment]
Hi @zfisher323 
I just never use UIImageWriteToSavedPhotosAlbum before 
I will try it and help you find the problem

**Comment by zfisher323** [comment]
That would be amazing... doesn't have to be UIImageWrite... the goal is just to simply be able to save that generated QR code to the photo album so then it can be emailed, printed, messaged, etc...

**Comment by heart** [comment]
Hello @zfisher323 
I dont't know what realy happn but this code will work
you need to create new image with new CIContext before put it to  UIImageWriteToSavedPhotosAlbum

```swift
//Don't use "!" to force unwrap it may crash your app
//Use if statement to unwrap it instead
if let image = self.barcodeImage {
  let ciImage = image.ciImage 
  let context = CIContext()

  //you can use "!" for ciImage because of it will never run to this line if 'self.barcodeImage' is nil
  let cgImage = context.createCGImage(ciImage!, from: ciImage!.extent) 
  let uiImage = UIImage(cgImage: cgImage!)
                    
  UIImageWriteToSavedPhotosAlbum(uiImage, nil, nil, nil)
}
```

**Comment by zfisher323** [comment]
works like a charm! buying you some coffee now!!
