### ISSUE TITLE
Missing argument for parameter 'onFound' in call

### ISSUE THREAD

**Issue by ThunZEN** [heart/CarBode-Barcode-Scanner-For-SwiftUI#36]
Hi I'm just starting to learn Swift

I can't figure out why the simplest scanner doesn't work
Xcode 11.3.1

<img width="753" alt="Снимок экрана 2020-11-06 в 20 45 54" src="https://user-images.githubusercontent.com/74058873/98380868-5a1b5280-2073-11eb-9c37-38e94b1775c5.png">

**Comment by heart** [comment]
please upgrade your xcode to 12.1
