### ISSUE TITLE
View takes long Time (async)

### ISSUE THREAD

**Issue by lutzmuschischutz** [heart/CarBode-Barcode-Scanner-For-SwiftUI#37]
Hello, the View to load the Scanner takes long time till to init the cam.
is there a way to init the cam after the view is presenting?
hope you know what i mean. Like Async

**Comment by heart** [comment]
Hi @lutzmuschischutz 
I see what you mean I will find the way to fix it

**Comment by heart** [comment]
Hi @lutzmuschischutz 

Please try v.2.2.1
https://github.com/heart/CarBode-Barcode-Scanner-For-SwiftUI/releases/tag/2.2.1

**Comment by lutzmuschischutz** [comment]
now it takes 10 seconds.
I mean if the view is appear the cam needs to load and turn on.
if view disappears the cam turn off.

**Comment by zfisher323** [comment]
I can confirm this issue still appears in version 2.2.1... I'm testing it on an iPhone 12 pro running 14.2 - the scanner view eventually opens, but it takes about 5-10 seconds to launch. It doesn't happen in Xcode 12.1 simulator... just one the actual iPhone 12 Pro... I had a friend test on an older iPad and there is the same 10 second delay - didn't occur before 2.2 as far as I can tell...

**Comment by heart** [comment]
Please try again on 2.2.2

**Comment by zfisher323** [comment]
This seems to be working better for me. Thanks for the quick turnaround!
