### ISSUE TITLE
Library Improvements

### ISSUE THREAD

**Issue by EstebanC02** [heart/CarBode-Barcode-Scanner-For-SwiftUI#4]
Hi, me again. Since you have control of the camera through the library, can you help me get the library to enable flash?

I have also seen that the application is required to restart even though it has the permission to use the camera, is there anything that can be done to activate the camera as soon as the permission is given by the user?

Thanks!

**Comment by heart** [comment]
Hello @EstebanC02 
Now you can enable the flashlight please update the library to v.1.2.0
