### ISSUE TITLE
Turn off Cam View Disappear

### ISSUE THREAD

**Issue by lutzmuschischutz** [heart/CarBode-Barcode-Scanner-For-SwiftUI#40]
Cam do not turn off if the View is disappearing or you go back to previous View.

**Comment by heart** [comment]
Hi @lutzmuschischutz 

The camera will stop when the view has been destroyed or removed from view hierarchy.

Please give me the code that I can reproduce your issue.

**Comment by manmal** [comment]
@heart The camera and barcode scanner stays active when another view is pushed via a NavigationLink. It seems that the underlying view is not destroyed in that case, leaving the CBScanner view fully active. Unfortunately I'm not in the position right now to setup a sample project.

**Comment by heart** [comment]
Thank you @manmal I will try to fix it

**Comment by manmal** [comment]
@heart I opened #44 which seems to address the problem for me.
