### ISSUE TITLE
Extra trailing closure passed in call

### ISSUE THREAD

**Issue by MarcoGT** [heart/CarBode-Barcode-Scanner-For-SwiftUI#46]
Following error appears with Xcode 12.5 beta 2

Extra trailing closure passed in call

ModalBarcodeGenerator.swift at Line 25

**Comment by vtaluskie** [comment]
FWIW, I'm seeing the same error building the example project with the released XCode 12.5

**Comment by heart** [comment]
Thankyou and sorry for my late. I just fixed this issue
