### ISSUE TITLE
Support "CODABAR" barcode type

### ISSUE THREAD

**Issue by xperad** [heart/CarBode-Barcode-Scanner-For-SwiftUI#49]
Does this library support the "Codabar" type? 
https://en.wikipedia.org/wiki/Codabar

I couldn't find this type on this library.
Would you have the plan to support this type of barcode?

Thank you

**Comment by MikeMilzz** [comment]
Codabar wasn't previously supported by AVFoundation or any projects based on Apple's built-in support. I haven't see if this will change with the updates to Foundation announced at WWDC 2021. For a previous project, I ended up using Google's MLKit to detect Codabar barcodes. Here's to hoping Apple adds native support for this format soon.
