### ISSUE TITLE
Slow closing of camera

### ISSUE THREAD

**Issue by ghost** [heart/CarBode-Barcode-Scanner-For-SwiftUI#5]
Hi,

I am using the scanner in a NavigationView -> NavigationLink.
If I open the camera from here it works fine.
When I want to close it by clicking the back arrow in NavigationView, it takes about 5 secs to close (showing the gray background meanwhile). Do other experience this also - or do I have (probably) some error in my code? :)

Thanks, Jens

**Comment by wesselpeder** [comment]
+1

**Comment by heart** [comment]
I'm working on this issue

**Comment by redlbull** [comment]
+1

**Comment by heart** [comment]
Sorry guy
My company have a lot of works I have to finish before the end of the year
I will fix it this weekend.

**Comment by liaochangjiang** [comment]
+1

**Comment by heart** [comment]
Hello @holtsmark @wesselpeder @redlbull @liaochangjiang 

I just fixed the bug please update the library
