### ISSUE TITLE
Incorrect Camera Orientation in Landscape on iPhone and iPad

### ISSUE THREAD

**Issue by MikeMilzz** [heart/CarBode-Barcode-Scanner-For-SwiftUI#51]
I saw there was a previously closed issue about camera orientation, but I am having an issue with version 2.2.2 where if I start a scan while the device is in landscape mode, the camera will be sideways. If I start a scan in portrait and rotate to landscape on an iPhone, the camera appears to rotate the image to the correct orientation. If I test on an iPad (12.9" Pro running 14.6), the camera is always sideways in landscape mode.

I'm happy to help test and do anything I can to track down this bug.
Thanks.

**Comment by heart** [comment]
Thankyou @MikeMilzz 

Can you please tell me when the device rotate to each side how the camera actual rotate

**Comment by MikeMilzz** [comment]
Thanks for the reply and for looking into this issue. 

iPhone top to the right - image is rotated to the left and legible (not mirrored); rotate to portrait and image is correct; rotate back to top on the right and image is correct - it's only the initial launch image

iPhone top to the left -  image is rotated to the right and legible (not mirrored); rotate to portrait and image is correct; rotate back to top on the left and image is correct - it's only the initial launch image

Hope that helps.

**Comment by MikeMilzz** [comment]
Just submitted a pull request (my first one ever, so let me know if I did it wrong). I think I found an easy fix that adds a single update of the self.updateCameraView() at the end of the CameraView setup.

**Comment by MikeMilzz** [comment]
Hi. Have you had a chance to look at my pull request to resolve this issue? It's a small one line change that should resolve this without introducing any issues. All my testing has been positive with this change.

**Comment by heart** [comment]
Hello @MikeMilzz Thankyou for your help I just merged your PR
