### ISSUE TITLE
10 second delay when showing CarBode view using modal .sheet() 

### ISSUE THREAD

**Issue by johncneal** [heart/CarBode-Barcode-Scanner-For-SwiftUI#6]
I get a 10 second delay before the CarBode view is displayed when launched from a modal .sheet(). The sheet is implemented in what appears to be the standard way with a @State variable and a button to set the boolean to launch the modal sheet.

I've got the CarBode view in a separate struct and it all works fine when the view is eventually displayed. 

I've even tried putting the view code 'in line' in my .sheet() but either way there is always a 10 sec delay before the view is shown.  

Anyone else seen this? Any suggestions for how to get rid of the 10 sec delay?
john

**Comment by heart** [comment]
Sorry to hear that.
My company have a lot of works I have to finish before end of year
I will fix it this weekend.

**Comment by johncneal** [comment]
No problem.
Not sure if its relevant but at the point the CarBode view is eventually shown I get the following in the XCode debug window -
2020-01-01 16:38:38.462674+0000 ClinPhoto[9172:3415494] [Common] _BSMachError: port 6903; (os/kern) invalid capability (0x14) "Unable to insert COPY_SEND"

But as I say, the app appears to work fine despite that.
j

**Comment by heart** [comment]
Hello @johncneal 

I just fixed the bug please update the library
