### ISSUE TITLE
'AVMetadataObject' is only available in Mac Catalyst 14.0 or newer

### ISSUE THREAD

**Issue by L1cardo** [heart/CarBode-Barcode-Scanner-For-SwiftUI#64]
Please consider to upgrade to `.iOS(.v14)`
https://github.com/heart/CarBode-Barcode-Scanner-For-SwiftUI/blob/23133e8a7caf11005e7b7a5724f4c3e327cf0a62/Package.swift#L9

<img width="330" alt="image" src="https://user-images.githubusercontent.com/33802186/141317614-c0bfbefd-3ec6-4701-bd98-701335fd3fc5.png">

**Comment by heart** [comment]
Hi @L1cardo This library support only iOS devices
Make sure your selected target is iOS, not macOS

**Comment by L1cardo** [comment]
As you can see, I am working on a catalyst project, which is actually some kind of iOS.🙂
